server:
  port: 8011
  servlet:
    context-path: /book
  #jsp-servlet:
    #init-parameters:
      #development: true
spring:
  #mvc:
    #view:
      #prefix: /WEB-INF/
      #suffix: .jsp
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/book?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      #监控统计拦截的filters
      filters: stat
      initial-size: 5
      min-idle: 5
      max-active: 10
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true

mybatis:
  config-location: classpath:/mybatis-config.xml
  mapper-locations: classpath*:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.*  # 注意：对应实体类的路径

#logging:
#  config: classpath:log4j2.xml


#shiro:
#  web:
#    enabled: true
#  loginUrl: /toLogin


